import Head from 'next/head'
// import 'bootstrap/dist/css/bootstrap.css'
import {questions} from "../../../data/questions";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

export default function Browse() {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          
        </div>

        <div className={styles.center}>
            <h2 className={inter.className}>Q: FlashCard</h2>
        </div>

        <div className={styles.grid}>
            <div
                className={styles.button}
            >
                <h2 className={inter.className}>
                <span>&lt;- Prev</span>
                </h2>
            </div>

            <Link
                href={`browse/${questions[0]._id.$oid}`}
                className={styles.button}
            >
                <h2 className={inter.className}>
                <span>Next -&gt;</span>
                </h2>
            </Link>
        </div>
      </main>
    </>
  )
}


