import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link';
import { Search } from 'tabler-icons-react';
import Navbar from './Navbar';


export default function Layout({children} : any) {
  
  return (
    <>
      <Head>
        <title>StudySmarter.AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        
        {children}

      </main>
    </>
  )
}


  